# Generated by Django 3.1.1 on 2020-09-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('House_No', models.IntegerField(blank=True, null=True)),
                ('Street_Address', models.CharField(max_length=200)),
                ('Postal_Address', models.CharField(max_length=200)),
                ('Postal_Code', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('phone_No', models.IntegerField(blank=True)),
                ('Status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.BigIntegerField(blank=True)),
                ('payment_type', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
