# Generated by Django 3.1.1 on 2020-09-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.AlterField(
            model_name='address',
            name='House_No',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customer_class',
            name='Email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
