# Generated by Django 3.1.1 on 2020-09-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20200927_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_class',
            name='Address',
        ),
    ]
