# Generated by Django 3.1.1 on 2020-09-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Id', models.IntegerField(blank=True, null=True)),
                ('Order_No', models.IntegerField(blank=True, null=True)),
                ('Product_details', models.CharField(max_length=20)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('Catagories', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer_class')),
                ('Product', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product_class')),
                ('order', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order_class')),
            ],
        ),
    ]
