# Generated by Django 3.1.1 on 2020-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20200929_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_class',
            name='Product_image',
        ),
        migrations.AddField(
            model_name='product_class',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.jpg', upload_to='products/images/'),
        ),
    ]
