# Generated by Django 3.1.1 on 2020-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_class',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='payment_class',
            name='payment_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
