# Generated by Django 3.1.1 on 2020-09-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fashion_Designer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion_designer_class',
            name='Customer',
        ),
        migrations.AddField(
            model_name='fashion_designer_class',
            name='Designer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
