# Generated by Django 3.1.1 on 2020-09-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_auto_20200929_0100'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_class',
            name='Payment',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.payment_class'),
        ),
    ]
