# Generated by Django 3.1.1 on 2020-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_class_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_class',
            name='order_image',
            field=models.ImageField(null='true', upload_to=''),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='order_class',
            name='order_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
