# Generated by Django 3.1.1 on 2020-10-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201003_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_class',
            name='order_details',
            field=models.CharField(default='', max_length=200),
        ),
    ]
